import json
import math
import os
import time
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts
from torch.utils.data import Dataset, DataLoader
from PIL import Image

from diffusers import (
    AutoencoderKL,
    ControlNetModel,
    DDPMScheduler,
    StableDiffusionControlNetPipeline,
    UNet2DConditionModel,
)
from transformers import CLIPTextModel, CLIPTokenizer

CSV_PATH      = os.environ.get("CSV_PATH",   "/workspace/captions.csv")
IMAGE_ROOT    = os.environ.get("IMAGE_ROOT", "/workspace/flickr30k-images")
OUTPUT_DIR    = Path(os.environ.get("OUTPUT_DIR", "/workspace/outputs"))
CKPT_DIR      = OUTPUT_DIR / "checkpoints"
INFER_DIR     = OUTPUT_DIR / "inference"

NUM_IMAGES       = int(os.environ.get("NUM_IMAGES",       "10000"))
BATCH_SIZE       = int(os.environ.get("BATCH_SIZE",       "8"))
NUM_EPOCHS       = int(os.environ.get("NUM_EPOCHS",       "5"))
LR               = float(os.environ.get("LR",             "1e-4"))
GRAD_ACCUM_STEPS = int(os.environ.get("GRAD_ACCUM_STEPS", "2"))
NUM_WORKERS      = int(os.environ.get("NUM_WORKERS",      "4"))
TIMESTEP_BIAS    = float(os.environ.get("TIMESTEP_BIAS",  "0.7"))

SD_ID           = "runwayml/stable-diffusion-v1-5"
CN_ID           = "lllyasviel/sd-controlnet-canny"
DTYPE           = torch.float32
IMAGE_SIZE      = 512   
MAX_TOK         = 77
VAE_SCALE       = 0.18215
GRID_SIZE       = 8
TEXT_DIM        = 768
TRAIN_CN_BLOCKS = {"down_blocks.2", "down_blocks.3", "mid_block"}


###########################################################################
# DATASET
###########################################################################

class FlickrSketchDataset(Dataset):
    """
    Loads Flickr30k image-caption pairs from captions.csv (generated by
    convert.py). Generates Canny edge sketch on-the-fly from each image.
    """
    def __init__(self, csv_path: str, image_root: str, max_samples: int = None):
        self.df         = pd.read_csv(csv_path)
        self.image_root = image_root
        if max_samples:
            self.df = self.df.head(max_samples)
        print(f"[Dataset] {len(self.df)} samples from {csv_path}")

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row        = self.df.iloc[idx]
        img_path   = os.path.join(self.image_root, row["image"])
        caption    = str(row["caption"])

        img = cv2.imread(img_path)
        if img is None:
            return self.__getitem__((idx + 1) % len(self.df))

        img = cv2.resize(img, (IMAGE_SIZE, IMAGE_SIZE), interpolation=cv2.INTER_LANCZOS4)


        gray    = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        blurred = cv2.GaussianBlur(gray, (5, 5), 0)
        edges   = cv2.Canny(blurred, 100, 200)
        edges3  = cv2.cvtColor(edges, cv2.COLOR_GRAY2RGB)


        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

       
        img_t   = torch.from_numpy(img_rgb.astype(np.float32)  / 127.5 - 1.0).permute(2, 0, 1)
        edge_t  = torch.from_numpy(edges3.astype(np.float32)   / 127.5 - 1.0).permute(2, 0, 1)

        return {"image": img_t, "edge_map": edge_t, "caption": caption}


def make_loader(csv_path, image_root, batch_size, num_workers, max_samples=None):
    ds = FlickrSketchDataset(csv_path, image_root, max_samples)
    return DataLoader(
        ds, batch_size=batch_size, shuffle=True,
        num_workers=num_workers, pin_memory=True,
        drop_last=True, persistent_workers=(num_workers > 0),
    )


###########################################################################
# REGION ATTENTION MODULES
###########################################################################

class RegionExtractor(nn.Module):
    def __init__(self, in_ch=1280, embed_dim=TEXT_DIM, grid=GRID_SIZE):
        super().__init__()
        self.pool = nn.AdaptiveAvgPool2d((grid, grid))
        self.proj = nn.Linear(in_ch, embed_dim)
        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x):
        x = x.float()
        x = self.pool(x).flatten(2).permute(0, 2, 1)
        return self.norm(self.proj(x))


class SemanticAttention(nn.Module):
    def __init__(self, dim=TEXT_DIM, dropout=0.1):
        super().__init__()
        self.scale   = math.sqrt(dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, regions, text):
        q = regions.float()
        k = text.float()
        w = F.softmax(torch.matmul(q, k.transpose(-1, -2)) / self.scale, dim=-1)
        return self.dropout(w)


class SafeAttnProcessor(nn.Module):
    def __init__(self, proc):
        super().__init__()
        self.proc = proc

    def __call__(self, attn, hidden_states, encoder_hidden_states=None,
                 attention_mask=None, temb=None, region_weights=None, **kw):
        return self.proc(attn, hidden_states,
                         encoder_hidden_states=encoder_hidden_states,
                         attention_mask=attention_mask, temb=temb, **kw)


class RegionAwareAttnProcessor(nn.Module):
    def __init__(self, grid=GRID_SIZE):
        super().__init__()
        self.grid  = grid
        self.scale = nn.Parameter(torch.tensor(0.0))

    def __call__(self, attn, hidden_states, encoder_hidden_states=None,
                 attention_mask=None, temb=None, region_weights=None, **kw):
        is_cross = encoder_hidden_states is not None
        B, S, D  = hidden_states.shape
        kv       = encoder_hidden_states if is_cross else hidden_states

        Q, K, V  = attn.to_q(hidden_states), attn.to_k(kv), attn.to_v(kv)
        hd       = D // attn.heads
        rshp     = lambda t: t.view(B, -1, attn.heads, hd).transpose(1, 2)
        Q, K, V  = rshp(Q), rshp(K), rshp(V)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(hd)

        if is_cross and region_weights is not None:
            scores = self._bias(scores, region_weights, B)

        if attention_mask is not None:
            scores = scores + attention_mask

        out = torch.matmul(F.softmax(scores, dim=-1), V)
        out = out.transpose(1, 2).reshape(B, -1, D)
        return attn.to_out[1](attn.to_out[0](out))

    def _bias(self, scores, rw, B):
        _, H, S_q, S_k = scores.shape
        _, R, T         = rw.shape
        T2  = min(S_k, T)
        rw2 = rw[:, :, :T2].permute(0, 2, 1)
        tgt = int(math.sqrt(S_q))

        if tgt * tgt == S_q:
            rw2 = rw2.view(B, T2, self.grid, self.grid)
            rw2 = F.interpolate(rw2, (tgt, tgt), mode="bilinear", align_corners=False)
            rw2 = rw2.flatten(2).permute(0, 2, 1)
        else:
            rw2 = F.interpolate(rw2.unsqueeze(1), (T2, S_q),
                                 mode="bilinear", align_corners=False
                                 ).squeeze(1).permute(0, 2, 1)

        if T2 < S_k:
            rw2 = F.pad(rw2, (0, S_k - T2))

        return scores + rw2.unsqueeze(1).to(scores.dtype) * self.scale


###########################################################################
# MODEL LOADING
###########################################################################

def load_models(device):
    print("=" * 60 + "\nLOADING MODELS\n" + "=" * 60)

    tok  = CLIPTokenizer.from_pretrained(SD_ID, subfolder="tokenizer")
    te   = CLIPTextModel.from_pretrained(SD_ID, subfolder="text_encoder",
                                          torch_dtype=DTYPE).to(device)
    _freeze(te, "TextEncoder")

    vae  = AutoencoderKL.from_pretrained(SD_ID, subfolder="vae",
                                          torch_dtype=DTYPE).to(device)
    _freeze(vae, "VAE")

    unet = UNet2DConditionModel.from_pretrained(SD_ID, subfolder="unet",
                                                 torch_dtype=DTYPE).to(device)
    _freeze(unet, "UNet")

    cn   = ControlNetModel.from_pretrained(CN_ID, torch_dtype=DTYPE).to(device)

    # Selective freeze: only last 2 blocks + mid_block
    for p in cn.parameters():
        p.requires_grad = False
    for name, p in cn.named_parameters():
        if any(blk in name for blk in TRAIN_CN_BLOCKS):
            p.requires_grad = True

    cn_total   = sum(p.numel() for p in cn.parameters())
    cn_trained = sum(p.numel() for p in cn.parameters() if p.requires_grad)
    print(f"  ControlNet: {cn_trained:,}/{cn_total:,} trainable "
          f"({100*cn_trained/cn_total:.1f}%)")

    re = RegionExtractor().to(device=device, dtype=DTYPE)
    sa = SemanticAttention().to(device=device, dtype=DTYPE)

    return dict(tok=tok, te=te, vae=vae, unet=unet, cn=cn, re=re, sa=sa)


def inject_attn(unet, device):
    new_procs, n = {}, 0
    for name, proc in unet.attn_processors.items():
        if "attn2" in name:
            new_procs[name] = RegionAwareAttnProcessor().to(device=device, dtype=DTYPE)
            n += 1
        else:
            new_procs[name] = SafeAttnProcessor(proc)
    unet.set_attn_processor(new_procs)
    print(f"  Injected {n} RegionAwareAttnProcessors")
    return n


def region_proc_params(unet):
    return [p for proc in unet.attn_processors.values()
            if isinstance(proc, RegionAwareAttnProcessor)
            for p in proc.parameters() if p.requires_grad]


def _freeze(m, name):
    for p in m.parameters():
        p.requires_grad = False
    print(f"  {name}: frozen")


###########################################################################
# METRICS
###########################################################################

def compute_metrics(pred, target):
    p   = pred.float().detach()
    t   = target.float().detach()
    mse = F.mse_loss(p, t).item()
    mae = F.l1_loss(p, t).item()
  
    psnr = 10 * math.log10((2.0 ** 2) / (mse + 1e-8))

    mu_p   = p.mean(); mu_t  = t.mean()
    sig_p  = p.var();  sig_t = t.var()
    sig_pt = ((p - mu_p) * (t - mu_t)).mean()
    c1, c2 = 0.01**2, 0.03**2
    ssim   = ((2*mu_p*mu_t + c1) * (2*sig_pt + c2)) / \
             ((mu_p**2 + mu_t**2 + c1) * (sig_p + sig_t + c2))

    return {"MSE": mse, "MAE": mae, "PSNR": psnr, "SSIM": ssim.item()}


def print_metrics(metrics_log, final, nan_count, train_time,
                  total_time, throughput, peak_vram, n_params):
    W = 65
    print("\n" + "=" * W)
    print(f"{'TRAINING METRICS':^{W}}")
    print("=" * W)
    print(f"\n{'Ep':>3} {'Loss':>10} {'MSE':>9} {'MAE':>9} {'PSNR':>9} {'SSIM':>9}")
    print("-" * W)
    for r in metrics_log:
        print(f"  {r['epoch']:>2}  {r['loss']:>10.6f} {r['MSE']:>9.6f} "
              f"{r['MAE']:>9.6f} {r['PSNR']:>9.3f} {r['SSIM']:>9.6f}")
    print("\n" + "-" * W)
    for k, v in [
        ("Final MSE",              f"{final.get('MSE',  0):.6f}"),
        ("Final MAE",              f"{final.get('MAE',  0):.6f}"),
        ("Final PSNR (dB)",        f"{final.get('PSNR', 0):.4f}"),
        ("Final SSIM",             f"{final.get('SSIM', 0):.6f}"),
        ("NaN steps skipped",      str(nan_count)),
        ("Training time (s)",      f"{train_time:.1f}"),
        ("Total runtime (s)",      f"{total_time:.1f}"),
        ("Throughput (img/s)",     f"{throughput:.2f}"),
        ("Peak VRAM (GB)",         f"{peak_vram:.2f}"),
        ("Trainable params",       f"{n_params:,}"),
    ]:
        print(f"  {k:<30} {v:>28}")
    print("=" * W)


###########################################################################
# TIMESTEP SAMPLING
###########################################################################

def sample_timesteps(bs, device, total=1000, bias=TIMESTEP_BIAS):
    n_low  = int(bs * bias)
    n_high = bs - n_low
    low    = torch.randint(0, total // 2,  (n_low,),  device=device)
    high   = torch.randint(total // 2, total, (n_high,), device=device)
    ts     = torch.cat([low, high])
    return ts[torch.randperm(bs, device=device)]


###########################################################################
# INFERENCE
###########################################################################

def run_inference(m, sched, device, sample_batch, epoch):
    INFER_DIR.mkdir(parents=True, exist_ok=True)
    print("\n[INFERENCE] Generating output image...")

    edges    = sample_batch["edge_map"]
    captions = sample_batch["caption"]

    pipe = StableDiffusionControlNetPipeline.from_pretrained(
        SD_ID, controlnet=m["cn"],
        torch_dtype=DTYPE, safety_checker=None,
    ).to(device)
    pipe.scheduler = sched
    pipe.set_progress_bar_config(disable=True)
    try:
        pipe.enable_xformers_memory_efficient_attention()
    except Exception:
        pass

    edge_np    = ((edges[0].permute(1, 2, 0).cpu().numpy() + 1.0) * 127.5
                  ).clip(0, 255).astype(np.uint8)
    sketch_pil = Image.fromarray(edge_np)
    prompt     = captions[0]
    print(f"[INFERENCE] Prompt: {prompt[:80]}")

    with torch.no_grad():
        result = pipe(
            prompt=prompt, image=sketch_pil,
            num_inference_steps=30, guidance_scale=7.5,
            height=IMAGE_SIZE, width=IMAGE_SIZE,
        ).images[0]

    out = INFER_DIR / f"generated_epoch{epoch}.png"
    inp = INFER_DIR / "input_sketch.png"
    result.save(str(out))
    sketch_pil.save(str(inp))
    print(f"[INFERENCE] Saved → {out}")
    return str(out)


###########################################################################
# MAIN TRAINING LOOP
###########################################################################

def main():
    print("=" * 60)
    print("DUAL-STAGE REGION-AWARE DIFFUSION — GCP Training")
    print(f"  Images: {NUM_IMAGES} | Epochs: {NUM_EPOCHS} | "
          f"Batch: {BATCH_SIZE} | LR: {LR}")
    print("=" * 60)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    CKPT_DIR.mkdir(parents=True, exist_ok=True)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[INFO] Device: {device}")
    if device == "cuda":
        print(f"[INFO] GPU:  {torch.cuda.get_device_name(0)}")
        print(f"[INFO] VRAM: {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB")

    t0 = time.time()

    loader = make_loader(CSV_PATH, IMAGE_ROOT, BATCH_SIZE, NUM_WORKERS, NUM_IMAGES)

    print(f"[DATA] Loading up to {NUM_IMAGES} images...")
    all_batches, loaded = [], 0
    for b in loader:
        all_batches.append(b)
        loaded += b["image"].shape[0]
        if loaded >= NUM_IMAGES:
            break
    print(f"[DATA] {loaded} images in {len(all_batches)} batches")

    m = load_models(device)
    inject_attn(m["unet"], device)
    sched = DDPMScheduler.from_pretrained(SD_ID, subfolder="scheduler")

    m["vae"].eval(); m["te"].eval()
    m["unet"].train(); m["cn"].train()
    m["re"].train();   m["sa"].train()

    trainable = (
        [p for p in m["cn"].parameters() if p.requires_grad] +
        [p for p in m["re"].parameters() if p.requires_grad] +
        [p for p in m["sa"].parameters() if p.requires_grad] +
        region_proc_params(m["unet"])
    )
    N_params = sum(p.numel() for p in trainable)
    print(f"\n[OPT] Trainable params: {N_params:,}")

    opt          = AdamW(trainable, lr=LR, weight_decay=1e-4)
    total_steps  = (NUM_EPOCHS * len(all_batches)) // GRAD_ACCUM_STEPS
    lr_sched     = CosineAnnealingWarmRestarts(opt, T_0=max(1, total_steps // NUM_EPOCHS))
    print(f"[SCHED] CosineWarmRestarts over {total_steps} optimizer steps")

    print(f"\n[TRAIN] {NUM_EPOCHS} epochs | {IMAGE_SIZE}px | float32 | "
          f"timestep bias {TIMESTEP_BIAS*100:.0f}%")
    print("-" * 60)

    t_train      = time.time()
    nan_count    = 0
    total_imgs   = 0
    metrics_log  = []
    last_metrics = {}
    global_step  = 0

    for epoch in range(1, NUM_EPOCHS + 1):
        ep_loss = ep_mse = ep_mae = ep_psnr = ep_ssim = 0.0
        steps   = 0

        for batch_idx, batch in enumerate(all_batches):
            imgs  = batch["image"].to(device=device, dtype=DTYPE)
            edges = batch["edge_map"].to(device=device, dtype=DTYPE)
            caps  = batch["caption"]
            bs    = imgs.shape[0]
            total_imgs += bs

            with torch.no_grad():
                latents = m["vae"].encode(imgs).latent_dist.sample() * VAE_SCALE

            noise     = torch.randn_like(latents)
            ts        = sample_timesteps(bs, device)
            noisy_lat = sched.add_noise(latents, noise, ts)

            with torch.no_grad():
                ids     = m["tok"](list(caps), padding="max_length",
                                    max_length=MAX_TOK, truncation=True,
                                    return_tensors="pt").input_ids.to(device)
                txt_emb = m["te"](ids)[0]

            down_res, mid_res = m["cn"](
                sample=noisy_lat, timestep=ts,
                encoder_hidden_states=txt_emb,
                controlnet_cond=edges, return_dict=False,
            )

            reg_emb = m["re"](mid_res)
            reg_w   = m["sa"](reg_emb, txt_emb)

            noise_pred = m["unet"](
                sample=noisy_lat, timestep=ts,
                encoder_hidden_states=txt_emb,
                down_block_additional_residuals=down_res,
                mid_block_additional_residual=mid_res,
                cross_attention_kwargs={"region_weights": reg_w},
            ).sample

            loss = F.mse_loss(noise_pred, noise) / GRAD_ACCUM_STEPS

            if torch.isnan(loss) or torch.isinf(loss):
                nan_count += 1
                opt.zero_grad()
                continue

            loss.backward()

            is_step = ((batch_idx + 1) % GRAD_ACCUM_STEPS == 0 or
                       batch_idx == len(all_batches) - 1)
            if is_step:
                torch.nn.utils.clip_grad_norm_(trainable, 1.0)
                opt.step()
                lr_sched.step()
                opt.zero_grad()
                global_step += 1

            unscaled = loss.item() * GRAD_ACCUM_STEPS
            ep_loss += unscaled
            met      = compute_metrics(noise_pred, noise)
            ep_mse  += met["MSE"]; ep_mae  += met["MAE"]
            ep_psnr += met["PSNR"]; ep_ssim += met["SSIM"]
            steps   += 1

        if steps > 0:
            last_metrics = {
                "loss": ep_loss/steps, "MSE": ep_mse/steps,
                "MAE":  ep_mae/steps,  "PSNR": ep_psnr/steps,
                "SSIM": ep_ssim/steps,
            }

        metrics_log.append({"epoch": epoch, **last_metrics})
        print(f"  Ep {epoch}/{NUM_EPOCHS} | "
              f"Loss {last_metrics.get('loss',0):.4f} | "
              f"MSE {last_metrics.get('MSE',0):.4f} | "
              f"PSNR {last_metrics.get('PSNR',0):.2f}dB | "
              f"SSIM {last_metrics.get('SSIM',0):.4f} | "
              f"LR {opt.param_groups[0]['lr']:.2e} | "
              f"{time.time()-t_train:.0f}s")

  
        ckpt_path = CKPT_DIR / f"checkpoint_epoch_{epoch}.pt"
        torch.save({
            "epoch":       epoch,
            "controlnet":  m["cn"].state_dict(),
            "re":          m["re"].state_dict(),
            "sa":          m["sa"].state_dict(),
            "metrics":     last_metrics,
        }, str(ckpt_path))
        print(f"  Checkpoint saved → {ckpt_path}")

    m["cn"].eval()
    run_inference(m, sched, device, all_batches[0], NUM_EPOCHS)

    t_end      = time.time()
    train_dur  = t_end - t_train
    throughput = total_imgs / train_dur if train_dur > 0 else 0
    peak_vram  = torch.cuda.max_memory_allocated() / 1e9 if device == "cuda" else 0.0

    print_metrics(metrics_log, last_metrics, nan_count,
                  train_dur, t_end - t0, throughput, peak_vram, N_params)

    print(f"\n[DONE] Outputs at {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
